sudo: false

language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

script:
    - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php bin/phpcs --config-set php_path php; fi;'
    - php bin/phpcs --report=full --standard=PSR2 --extensions=php --encoding=utf-8 debug.php

before_script:
    - composer install --no-interaction --dev --prefer-source

